INSERT INTO USERS VALUES('kuku','root1234',true);
INSERT INTO AUTHORITIES VALUES(NULL,'kuku','ROLE_USER');
INSERT INTO AUTHORITIES VALUES(NULL,'kuku','ROLE_ADMIN');
INSERT INTO USER_INFO VALUES('kuku','Jacob','Guzmán Acosta','1988-02-24','M');

