CREATE TABLE USERS(
USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(50) NOT NULL,
ENABLED BIT NOT NULL
);

CREATE TABLE AUTHORITIES(
AUTHORITY_ID INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
AUTHORITY VARCHAR(50) NOT NULL,
CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME));

CREATE TABLE USER_INFO(
USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
LAST_NAME VARCHAR(30),
BIRTHDAY DATE NOT NULL,
SEX CHAR(1),
CONSTRAINT FK_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME));
);

CREATE TABLE POST(
POST_ID INT(4) NOT NULL PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(50) NOT NULL,
DATE_POST DATE NOT NULL,
TITLE VARCHAR(70) NOT NULL,
CATEGORY VARCHAR(50) NOT NULL,
CONTENT VARCHAR(2000) NOT NULL,
URL_IMAGE VARCHAR(100),
CONSTRAINT FK_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME));
);
